#!/bin/bash
Fail()
{
    echo "FATAL($0): $1"
    exit 1
}

# https://github.com/dotnet/sdk/issues/30624#issuecomment-1432118204
dotnet build --property:OutputPath="${PWD}/exe" || Fail "Error building csdown"
