#!/bin/bash
Fail()
{
    echo "FATAL($0): $1"
    exit 1
}

RunDemo()
{
    java -jar build/libs/astronomy-demo-1.0.0.jar $*
}

rm -rf build test
mkdir -p test
./gradlew jar || Fail "Cannot build jar file."
echo ""
echo "Java demos: starting"
echo ""

RunDemo now || Fail "Error running test: now"
RunDemo moonphase 2019-06-15T09:15:32.987Z > test/moonphase.txt || Fail "Error running test: moonphase"
diff {test,correct}/moonphase.txt || Fail "Incorrect output: moonphase"

echo ""
echo "Java demos: PASS"
exit 0
