#!/bin/bash
Fail()
{
    echo "FATAL($0): $1"
    exit 1
}

rm -rf build test
mkdir -p test
if ! ./gradlew jar test; then
    cat build/test-results/test/TEST-io.github.cosinekitty.astronomy.demo.MainTests.xml
    exit 1
fi
echo ""
echo "Java demos: starting"
echo ""

./rundemo now || Fail "Error running test: now"

./rundemo moonphase 2019-06-15T09:15:32.987Z > test/moonphase.txt || Fail "Error running test: moonphase"
diff {test,correct}/moonphase.txt || Fail "Incorrect output: moonphase"

./rundemo seasons 2019 > test/seasons.txt || Fail "Error running test: seasons"
diff {test,correct}/seasons.txt || Fail "Incorrect output: seasons"

echo ""
echo "Java demos: PASS"
exit 0
