#!/bin/bash

if [[ "$1" == "debug" ]]; then
    BUILDOPT='-g -Og'
else
    BUILDOPT='-O3'
fi

rm -f raytrace

g++ -Wall -Werror -x c++ -std=c++11 -o raytrace $BUILDOPT \
    -I.. -I../../../source/c \
    *.cpp ../astro_demo_common.c ../../../source/c/astronomy.c
