#!/bin/bash
Fail()
{
    echo "FATAL($(realpath $0)): $1"
    exit 1
}

node moonphase.js 2019-06-15T09:15:32.987Z > test/moonphase.txt || Fail "Error running moonphase.js."
diff test/moonphase.txt test/moonphase_correct.txt || Fail "Error comparing moonphase.js output."

node positions.js +45.6 -90.7 2018-11-30T17:55:07.234Z > test/positions.txt || Fail "Error running positions.js."
diff test/positions.txt test/positions_correct.txt || Fail "Error comparing positions.js output."

echo "PASS: nodejs examples"
exit 0
