#!/bin/bash
Fail()
{
    echo "FATAL($(realpath $0)): $1"
    exit 1
}

node positions.js 45 -90 2019-02-28T14:50:30.567Z > test/positions.txt || Fail "Error testing positions.js"
diff test/positions.txt test/positions_correct.txt || Fail "Error comparing positions.txt to positions_correct.txt"
echo "PASS: nodejs examples"
exit 0
