#!/bin/bash
Fail()
{
    echo "FATAL($0): $1"
    exit 1
}

if [[ "$1" == "debug" ]]; then
    BUILDOPT='-g -O0'
elif [[ -z "$1" ]]; then
    BUILDOPT='-O3'
else
    Fail "unrecognized command line option"
fi

for name in moonphase positions riseset seasons culminate horizon; do
    gcc ${BUILDOPT} -Wall -Werror -o ${name} -I../../source/c ../../source/c/astronomy.c astro_demo_common.c ${name}.c -lm ||
        Fail "Error building ${name}.c"
done

exit 0
