#!/bin/bash
Fail()
{
    echo "FATAL(demo/c/demotest): $1"
    exit 1
}

rm -f test/*.txt
mkdir -p test
./build || Fail "Error building example programs."

echo "Testing example: camera.c"
bin/camera 29 -81 2021-03-22T02:45:00Z > test/camera.txt || Fail "Error testing camera.c."
diff {correct,test}/camera.txt || Fail "Error comparing camera.c output."

echo "Testing example: moonphase.c"
bin/moonphase 2019-06-15T09:15:32.987Z > test/moonphase.txt || Fail "Error testing moonphase.c."
diff {correct,test}/moonphase.txt || Fail "Error comparing moonphase.c output."

echo "Testing example: positions.c"
bin/positions +45.6 -90.7 2018-11-30T17:55:07.234Z > test/positions.txt || Fail "Error testing positions.c."
diff {correct,test}/positions.txt || Fail "Error comparing positions.c output."

# Another test to check for a problem I found with putting "60" in the seconds field.
bin/positions 20.8 -75.2 2020-07-09T08:30:00Z > test/positions2.txt || Fail "Error in second call to positions.c."
diff {correct,test}/positions2.txt || Fail "Error comparing positions.c output #2."

echo "Testing example: riseset.c"
bin/riseset 45 -90 2019-06-14T21:45:25Z > test/riseset.txt || Fail "Error testing riseset.c."
diff {correct,test}/riseset.txt || Fail "Error comparing riseset.c output."

echo "Testing example: seasons.c"
bin/seasons 2020 > test/seasons.txt || Fail "Error testing seasons.c."
diff {correct,test}/seasons.txt || Fail "Error comparing seasons.c output."

echo "Testing example: culminate.c"
bin/culminate +30 -90 2015-02-28T00:00:00Z > test/culminate.txt || Fail "Error testing culminate.c."
diff {correct,test}/culminate.txt || Fail "Error comparing culminate.c output."

echo "Testing example: horizon.c"
bin/horizon +25.5 -85.3 2016-12-25T12:30:45Z > test/horizon.txt || Fail "Error testing horizon.c."
diff {correct,test}/horizon.txt || Fail "Error comparing horizon.c output."

echo "Testing example: lunar_eclipse.c"
bin/lunar_eclipse 1988-01-01T00:00:00Z > test/lunar_eclipse.txt || Fail "Error running lunar_eclipse.c."
diff {correct,test}/lunar_eclipse.txt || Fail "Error comparing lunar_eclipse.c output."

echo "Testing example: galactic.c"
bin/galactic 38.92056 -77.0658 22.793498 197.070510 2025-04-06T00:00:00Z > test/galactic.txt || Fail "Error running galactic.c."
diff {correct,test}/galactic.txt || Fail "Error comparing galactic.c output."

echo "Testing example: triangulate.c"
bin/triangulate 48.16042 24.49986 2019 18 7 48.27305 24.36401 662 83 12 > test/triangulate.txt || Fail "Error running triangulate.c."
diff {correct,test}/triangulate.txt || Fail "Error comparing triangulate.c output."

echo "Testing example: gravity.c"
for latitude in {0..90}; do
    bin/gravity ${latitude} 0 >> test/gravity.txt || Fail "Error running gravity.c."
done
diff {correct,test}/gravity.txt || Fail "Error comparing gravity.c output."

cd raytrace || Fail "error changing to raytrace directory"
./build || Fail "build raytracer"
./run || Fail "run raytracer"
cd ..

./run_worldmap || Fail "error in run_worldmap"

echo "PASS: C examples"
exit 0
