#!/bin/bash

[[ -z "${CC}" ]] && CC=gcc
echo "$0: C compiler = ${CC}"

if [[ "$1" == "debug" ]]; then
    BUILDOPT='-g -O0'
elif [[ -z "$1" ]]; then
    BUILDOPT='-O3'
else
    echo "FATAL(buildcode): unrecognized command line option"
    exit 1
fi

${CC} ${BUILDOPT} -Wall -Werror -o generate -I novas -I vsop \
    generate.c \
    earth.c \
    astro_vector.c \
    chebyshev.c \
    codegen.c \
    ephfile.c \
    vsop/vsop.c \
    novas/novas.c \
    novas/novascon.c \
    novas/nutation.c \
    novas/readeph0.c \
    novas/solsys1.c \
    novas/eph_manager.c \
    -lm || exit $?

echo "$0: Built 'generate' program."
exit 0
