#!/bin/bash

./ctest $1 diff 5.6e-17 temp/c_check.txt dotnet/csharp_test/csharp_check.txt || exit $?
./ctest $1 diff 1.2e-12 temp/{c,js}_check.txt || exit $?
./ctest $1 diff 5.1e-14 temp/{c,py}_check.txt || exit $?
./ctest $1 diff 1.2e-12 temp/{js,py}_check.txt || exit $?

echo ""
echo "diffcalc: PASS"
exit 0
