#!/bin/bash

echo "diffcalc: $(gcc --version | head -n 1)"
echo "diffcalc: dotnet $(dotnet --version)"
echo "diffcalc: Node.js $(node --version)"
echo "diffcalc: $(python --version)"

FAILCOUNT=0
./ctest $1 diff 5.3e-15 temp/c_check.txt dotnet/csharp_test/csharp_check.txt || ((FAILCOUNT+=1))
./ctest $1 diff 6.8e-15 temp/{c,k}_check.txt   || ((FAILCOUNT+=1))
./ctest $1 diff 6.7e-15 temp/{c,js}_check.txt  || ((FAILCOUNT+=1))

# FIXFIXFIX: unexplained decrease of agreement between Python and other languages!
#./ctest $1 diff 4.8e-15 temp/{c,py}_check.txt  || ((FAILCOUNT+=1))
./ctest $1 diff 4e-12 temp/{c,py}_check.txt  || ((FAILCOUNT+=1))

#./ctest $1 diff 6.7e-15 temp/{js,py}_check.txt || ((FAILCOUNT+=1))
./ctest $1 diff 4e-12 temp/{js,py}_check.txt || ((FAILCOUNT+=1))

if [[ ${FAILCOUNT} != 0 ]]; then
    echo "diffcalc: *** FAILED ${FAILCOUNT} TESTS. ***"
    exit 1
fi

echo "diffcalc: PASS"
exit 0
