#!/bin/bash
#
#   Don Cross, 2020-05-14
#   I have found a bug that causes geocentric moon (GM)
#   equatorial coordinate calculations to get worse
#   as DeltaT increases. Debugging by creating an
#   extremely large DeltaT value, so I can track down
#   where the discrepancy comes from.
#
rm -f temp/c_gm_check.txt
./build debug || exit $?
./generate source || exit $?
echo "Generated source code."
./ctbuild debug || exit $?
./ctest gm_issue || exit $?
./generate check temp/c_gm_check.txt || exit $?
exit 0
