#!/bin/bash
Fail()
{
    echo "ERROR($0): $1"
    exit 1
}

echo "Generating target code."
./generate source || Fail "Problem generating target code."

echo "Generating JS documentation in Markdown format."
jsdoc2md --separators --template ../jsdoc2md/js.hbs --files ../source/js/astronomy.js > ../source/js/README.md || Fail "Error generating JS documentation."

if [[ -d html ]]; then
    echo "Generating JS documentation in HTML format for local viewing."
    rm -rf html
    jsdoc ../source/js/astronomy.js --destination html || Fail "Error generating HTML preview"
else
    echo "(Skipping local HTML generation because html directory does not exist.)"
fi

echo "Generating C documentation"

cd ../source/c || Fail "Error changing directory to ../source/c"
rm -rf html xml latex
doxygen Doxyfile > doxygen.log || Fail "Error in doxygen"
moxygen -o README.md ./xml > moxygen.log || Fail "Error in moxygen"

# Temporary hack to fix broken link in moxygen output.
# See: https://github.com/sourcey/moxygen/issues/41
sed -i 's,https://sourcey.com/moxygen,https://github.com/sourcey/moxygen,g' README.md || Fail "Error in sed command"

exit 0
