#!/bin/bash
Fail()
{
    echo "ERROR($0): $1"
    exit 1
}

echo ""
echo "Generating target code."
./generate source || Fail "Problem generating target code."

echo ""
echo "Running seasons test."
node seasons_test.js || Fail "Failed seasons test."

echo ""
echo "Running rise/set test."
node rise_set_test.js || Fail "Failed rise/set test."

echo ""
echo "Running astro_check."
node astro_check.js > temp/check.txt || Fail "Problem running JavaScript unit test."
echo "Verifying astro_check output."
./generate check temp/check.txt || Fail "Verification failure for JavaScript unit test output."

echo ""
echo "Running check against JPL Horizons data."
./jplcheck || Fail "Error in JPL check."

echo ""
echo "Running test of moon phase search."
node moon_phase_test.js || Fail "Failed moon phase test."

echo ""
echo "SUCCESS."
exit 0
