#!/bin/bash
Fail()
{
    echo "ERROR($0): $1"
    exit 1
}

[[ "$1" == "" || "$1" == "-v" ]] || Fail "Invalid command line options."

rm -f temp/c_gm_check.txt
./ctbuild || exit 1
time ./ctest $1 check || Fail "Failure in ctest check"
./generate check temp/c_check.txt || Fail "Verification failure for C unit test output."
./ctest $1 all || Fail "Failure in C unit tests"

for file in temp/c_longitude_*.txt; do
    ./generate $1 check ${file} || Fail "Failed verification of file ${file}"
done

echo "unit_test_c: success"
exit 0
