#!/bin/bash
Fail()
{
    echo "ERROR($0): $1"
    exit 1
}

[[ "$1" == "" || "$1" == "-v" ]] || Fail "Invalid command line options."

time node test.js astro_check > temp/js_check.txt || Fail "Problem running JavaScript astro_check."
./generate $1 check temp/js_check.txt || Fail "Verification failure for JavaScript unit test output."

echo ""
echo "$0: Running check against JPL Horizons data."
./jplcheck || Fail "Error in JPL check."

node test.js $1 moon_phase || Fail "Failed moon phase test."
node test.js $1 lunar_apsis || Fail "Failed lunar apsis test."
node test.js $1 lunar_eclipse || Fail "Failed lunar eclipse test."
node test.js $1 planet_apsis || Fail "Failed planet apsis test."
node test.js $1 elongation || Fail "Failed longitude tests."

echo ""
echo "$0: Verifying elong_test output."
for file in temp/js_longitude_*.txt; do
    ./generate $1 check ${file} || Fail "Failed verification of ${file}"
done

node test.js $1 seasons || Fail "Failed seasons test."
node test.js $1 rise_set || Fail "Failed rise/set test."
node mag_test.js $1 || Fail "Failed magnitude tests."
node rotation.js $1 || Fail "Failed rotation tests."
node constellation.js || Fail "Failed constellation tests."

echo ""
echo "$0: SUCCESS."
exit 0
