#!/bin/bash
Fail()
{
    echo "ERROR($0): $1"
    exit 1
}

[[ "$1" == "" || "$1" == "-v" ]] || Fail "Invalid command line options."

cd ../source/kotlin || Fail "Cannot change dir to ../source/kotlin"
rm -rf build
./gradlew assemble build test dokkaGfm || Fail "Error building/testing Kotlin code."

# The above gradlew call also generated all the Markdown documentation.
# The other languages do this from makedoc, but Kotlin is an exception.
# Finish putting together custom documentation for GitHub.
cd ../../generate/kotlindoc || Fail "Cannot change dir to ../../generate/kotlindoc"
./format_kotlin_doc.py || Fail "Error running ./format_kotlin_doc.py"

#for file in temp/kotlin_longitude_*.txt; do
#    ./generate $1 check ${file} || Fail "Failed verification of file ${file}"
#done

echo "unit_test_kotlin: success"
exit 0
