#!/bin/bash
Fail()
{
    echo "ERROR($0): $1"
    exit 1
}

[[ "$1" == "" || "$1" == "-v" ]] || Fail "Invalid command line options."

go version || Fail "Cannot find Go compiler."

cd ../source/golang
go test || Fail "Failure in Go unit tests."
cd ../../generate
echo "unit_test_golang: success"
exit 0
