#!/bin/bash
Fail()
{
    echo "ERROR($0): $1"
    exit 1
}

python3 --version || Fail "Cannot print python version"
python3 test.py time || Fail "Failure reported by test.py (time)"
python3 test.py apsis || Fail "Failed Python apsis tests."
python3 test.py magnitude || Fail "Failed Python magnitude tests."
python3 test.py moon || Fail "Failure reported by test.py (moon)"
python3 test.py seasons seasons/seasons.txt || Fail "Failed Python seasons test."
python3 test.py moonphase moonphase/moonphases.txt || Fail "Failed Python moon phase test."
python3 test.py riseset riseset/riseset.txt || Fail "Failed Python rise/set tests."

python3 test.py elongation || Fail "Failed Python elongation tests."
for file in temp/py_longitude_*.txt; do
    ./generate check ${file} || Fail "Failed verification of file ${file}"
    echo ""
done

echo "$0: Generating Python test output."
time python3 test.py astro_check > temp/py_check.txt || Fail "Failure in Python astro_check"
./generate check temp/py_check.txt || Fail "Verification failure for Python unit test output."
./ctest diff temp/{py,c}_check.txt || Fail "Diff(py,js) failure."

exit 0
