#!/bin/bash
Fail()
{
    echo "ERROR($0): $1"
    exit 1
}

echo "unit_test_csharp: Starting."
cd dotnet/csharp_test || "Cannot change to directory dotnet/csharp_test"
dotnet restore || Fail "Error in dotnet restore"
dotnet run || Fail "Error in dotnet run of csharp unit test"
cd ../..
./generate check dotnet/csharp_test/csharp_check.txt || Fail "Verification failure for C# unit test output."
for file in dotnet/csharp_test/csharp_longitude_*.txt; do
    ./generate check ${file} || Fail "Failed verification of file ${file}"
    echo ""
done
echo "unit_test_csharp: PASS."
exit 0
