#!/bin/bash
Fail()
{
    echo "FATAL($0): $1"
    exit 1
}

cp ../../../source/js/astronomy.{ts,d.ts} . || Fail "Error copying astronomy TypeScript code."
npm test || Fail "Error in unit test."
exit 0
