#!/bin/bash
Fail()
{
    echo "FATAL($(realpath $0)): $1"
    exit 1
}

rm -f moonphase positions
./build || Fail "Error building example programs."

./moonphase 2019-06-15T09:15:32.987Z > test/moonphase.txt || Fail "Error running moonphase.c program."
diff test/moonphase.txt test/moonphase_correct.txt || Fail "Error comparing moonphase.c output."

./positions +45.6 -90.7 2018-11-30T17:55:07.234Z > test/positions.txt || Fail "Error running positions test."
diff test/positions.txt test/positions_correct.txt || Fail "Error comparing positions.c output."
echo "PASS: C examples"
exit 0
