#!/bin/bash
Fail()
{
    echo "FATAL($0): $1"
    exit 1
}

IsInstalled()
{
    type "$1" > /dev/null 2>&1
    return $?
}

echo "Kotlin demos: Native"
cd native || Fail "Cannot cd to dir: native"

AESOURCE=../../../source/kotlin/src/main/kotlin/io/github/cosinekitty/astronomy/astronomy.kt

if [[ -x ../../../bin/kotlin-native/bin/kotlinc-native ]]; then
    KOTLIN_NATIVE=../../../bin/kotlin-native/bin/kotlinc-native
else
    KOTLIN_NATIVE=kotlinc-native
fi

echo "KOTLIN_NATIVE=$KOTLIN_NATIVE"

rm -f *.kexe
$KOTLIN_NATIVE -version || Fail "Cannot run Kotlin Native compiler."
$KOTLIN_NATIVE moonphase.kt $AESOURCE -o moonphase || Fail "Error building moonphase demo."
./moonphase.kexe || Fail "Error running moonphase demo."
cd ..

echo "Kotlin demos: PASS"
exit 0
