#!/bin/bash
Fail()
{
    echo "FATAL($0): $1"
    exit 1
}

TestDemo()
{
    echo "Testing Kotlin demo: $1"
    ./rundemo $* > test/$1.txt || Fail "Error running demo: $1"
    diff {correct,test}/$1.txt || Fail "Incorrect output: $1"
}

echo "Kotlin demos: starting"
rm -rf build test
mkdir -p test
./gradlew jar || Fail "Error building Kotlin demo application."

TestDemo constellation 2021-06-01T00:00:00Z
TestDemo jupiter_moons 2021-04-16T00:26:18Z
TestDemo moonphase 2019-06-15T09:15:32.987Z
TestDemo positions +45.6 -90.7 2018-11-30T17:55:07.234Z
TestDemo riseset +45.6 -90.7 2018-11-30T17:55:07.234Z
TestDemo seasons 2019

echo "Kotlin demos: PASS"
exit 0
