#!/bin/bash
Fail()
{
    echo "FATAL($0): $1"
    exit 1
}
rm -rf exe
rm -f test/{moonphase,positions,riseset,seasons,culminate,horizon}.txt
dotnet build --output ${PWD}/exe || Fail "Error building ${PWD}/demo.sln"

echo "Testing example: moonphase.cs"
dotnet exe/moonphase.dll 2019-06-15T09:15:32.987Z > test/moonphase.txt || Fail "Error testing moonphase.cs"
diff test/moonphase.txt test/moonphase_correct.txt || Fail "Error comparing moonphase.cs output."

echo "Testing example: positions.cs"
dotnet exe/positions.dll +45.6 -90.7 2018-11-30T17:55:07.234Z > test/positions.txt || Fail "Error testing positions.cs"
diff test/positions.txt test/positions_correct.txt || Fail "Error comparing positions.cs output."

echo "Testing example: culminate.cs"
dotnet exe/culminate.dll +30 -90 2015-02-28T00:00:00Z > test/culminate.txt || Fail "Error testing culminate.cs."
diff test/culminate.txt test/culminate_correct.txt || Fail "Error comparing culminate.cs output."

echo "PASS: C# examples"
exit 0
